// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 1.0.0
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.Utility.Logging;
using Kae.DomainModel.Csharp.Framework;
using Kae.DomainModel.Csharp.Framework.Adaptor.ExternalStorage;

namespace ActionLogicGenerationTest
{
    public partial class DomainClassBBase : DomainClassB
    {
        protected static readonly string className = "B";

        public string DomainName { get { return CIMActionLogicGenerationTestLib.DomainName; }}
        public string ClassName { get { return className; } }

        InstanceRepository instanceRepository;
        protected Logger logger;


        public string GetIdForExternalStorage() {  return $"B_ID={attr_B_ID}"; }

        public static DomainClassBBase CreateInstance(InstanceRepository instanceRepository, Logger logger=null, IList<ChangedState> changedStates=null, bool synchronousMode = false)
        {
            var newInstance = new DomainClassBBase(instanceRepository, logger, synchronousMode);
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:B(B_ID={newInstance.Attr_B_ID}):create");

            instanceRepository.Add(newInstance);

            if (changedStates !=null) changedStates.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Create, Target = newInstance, ChangedProperties = null });

            return newInstance;
        }

        public DomainClassBBase(InstanceRepository instanceRepository, Logger logger, bool synchronousMode)
        {
            this.instanceRepository = instanceRepository;
            this.logger = logger;
            attr_B_ID = Guid.NewGuid().ToString();
            stateof_B_ID = true;
        }
        protected string attr_B_ID;
        protected bool stateof_B_ID = false;

        protected string attr_A_ID;
        protected bool stateof_A_ID = false;

        protected int attr_NumberOfC;
        protected bool stateof_NumberOfC = false;

        protected DomainTypeKindOfB attr_Kind;
        protected bool stateof_Kind = false;

        public string Attr_B_ID { get { return attr_B_ID; } set { attr_B_ID = value; stateof_B_ID = true; } }
        public string Attr_A_ID { get { return attr_A_ID; } }
        public int Attr_NumberOfC
        {
            protected set { attr_NumberOfC = value; stateof_NumberOfC = true; }
            get
            {
                // Line : 1
                var c_set = this.LinkedR2() as List<DomainClassC>;

                // Line : 2
                this.Attr_NumberOfC = c_set.Count();

                return attr_NumberOfC;
            }
        }
        public DomainTypeKindOfB Attr_Kind { get { return attr_Kind; } set { attr_Kind = value; stateof_Kind = true; } }


        // This method can be used as compare predicattion when calling InstanceRepository's SelectInstances method. 
        public static bool Compare(DomainClassB instance, IDictionary<string, object> conditionPropertyValues)
        {
            bool result = true;
            foreach (var propertyName in conditionPropertyValues.Keys)
            {
                switch (propertyName)
                {
                    case "B_ID":
                        if ((string)conditionPropertyValues[propertyName] != instance.Attr_B_ID)
                        {
                            result = false;
                        }
                        break;
                    case "A_ID":
                        if ((string)conditionPropertyValues[propertyName] != instance.Attr_A_ID)
                        {
                            result = false;
                        }
                        break;
                    case "NumberOfC":
                        if ((int)conditionPropertyValues[propertyName] != instance.Attr_NumberOfC)
                        {
                            result = false;
                        }
                        break;
                    case "Kind":
                        if ((DomainTypeKindOfB)conditionPropertyValues[propertyName] != instance.Attr_Kind)
                        {
                            result = false;
                        }
                        break;
                }
                if (result== false)
                {
                    break;
                }
            }
            return result;
        }
        protected LinkedInstance relR1A;
        public DomainClassA LinkedR1()
        {
            if (relR1A == null)
            {
                var candidates = instanceRepository.GetDomainInstances("A").Where(inst=>(this.Attr_A_ID==((DomainClassA)inst).Attr_A_ID));
                if (candidates.Count() == 0)
                {
                   if (instanceRepository.ExternalStorageAdaptor != null) candidates = instanceRepository.ExternalStorageAdaptor.CheckTraverseStatus(DomainName, this, "A", "R1", candidates, () => { return DomainClassABase.CreateInstance(instanceRepository, logger); }, "any").Result;
                }
                relR1A = new LinkedInstance() { Source = this, Destination = candidates.FirstOrDefault(), RelationshipID = "R1", Phrase = "" };

            }
            return relR1A.GetDestination<DomainClassA>();
        }

        public bool LinkR1(DomainClassA instance, IList<ChangedState> changedStates=null)
        {
            bool result = false;
            if (relR1A == null)
            {
                this.attr_A_ID = instance.Attr_A_ID;
                this.stateof_A_ID = true;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:B(B_ID={this.Attr_B_ID}):link[A(A_ID={instance.Attr_A_ID})]");

                result = (LinkedR1()!=null);
                if (result)
                {
                    if(changedStates != null) changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Create, Target = relR1A });
                }
            }
            return result;
        }

        public bool UnlinkR1(DomainClassA instance, IList<ChangedState> changedStates=null)
        {
            bool result = false;
            if (relR1A != null && ( this.Attr_A_ID==instance.Attr_A_ID ))
            {
                if (changedStates != null) changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Delete, Target = relR1A });
        
                this.attr_A_ID = null;
                this.stateof_A_ID = true;
                relR1A = null;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:B(B_ID={this.Attr_B_ID}):unlink[A(A_ID={instance.Attr_A_ID})]");


                result = true;
            }
            return result;
        }

        public IEnumerable<DomainClassC> LinkedR2()
        {
            var result = new List<DomainClassC>();
            var candidates = instanceRepository.GetDomainInstances("C").Where(inst=>(this.Attr_B_ID==((DomainClassC)inst).Attr_B_ID));
            if (instanceRepository.ExternalStorageAdaptor != null) candidates = instanceRepository.ExternalStorageAdaptor.CheckTraverseStatus(DomainName, this, "C", "R2", candidates, () => { return DomainClassCBase.CreateInstance(instanceRepository, logger); }, "many").Result;
            foreach (var c in candidates)
            {
                ((DomainClassC)c).LinkedR2();
                result.Add((DomainClassC)c);
            }
            return result;
        }



        
        public bool Validate()
        {
            bool isValid = true;
            if (relR1A == null)
            {
                isValid = false;
            }
            return isValid;
        }

        public void DeleteInstance(IList<ChangedState> changedStates=null)
        {
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:B(B_ID={this.Attr_B_ID}):delete");

            changedStates.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Delete, Target = this, ChangedProperties = null });

            instanceRepository.Delete(this);
        }

        // methods for storage
        public void Restore(IDictionary<string, object> propertyValues)
        {
            if (propertyValues.ContainsKey("B_ID"))
            {
// should adopt timer setting
                attr_B_ID = (string)propertyValues["B_ID"];
            }
            stateof_B_ID = false;
            if (propertyValues.ContainsKey("A_ID"))
            {
// should adopt timer setting
                attr_A_ID = (string)propertyValues["A_ID"];
            }
            stateof_A_ID = false;
            if (propertyValues.ContainsKey("NumberOfC"))
            {
// should adopt timer setting
                attr_NumberOfC = (int)propertyValues["NumberOfC"];
            }
            stateof_NumberOfC = false;
            if (propertyValues.ContainsKey("Kind"))
            {
// should adopt timer setting
                attr_Kind = (DomainTypeKindOfB)propertyValues["Kind"];
            }
            stateof_Kind = false;
        }
        
        public IDictionary<string, object> ChangedProperties()
        {
            var results = new Dictionary<string, object>();
            if (stateof_B_ID)
            {
                results.Add("B_ID", attr_B_ID);
                stateof_B_ID = false;
            }
            if (stateof_A_ID)
            {
                results.Add("A_ID", attr_A_ID);
                stateof_A_ID = false;
            }
            if (stateof_NumberOfC)
            {
                results.Add("NumberOfC", attr_NumberOfC);
                stateof_NumberOfC = false;
            }
            if (stateof_Kind)
            {
                results.Add("Kind", attr_Kind.ToString());
                stateof_Kind = false;
            }

            return results;
        }

        public string GetIdentities()
        {
            string identities = $"B_ID={this.Attr_B_ID}";

            return identities;
        }
        
        public IDictionary<string, object> GetProperties(bool onlyIdentity)
        {
            var results = new Dictionary<string, object>();

            if (!onlyIdentity) results.Add("B_ID", attr_B_ID);
            if (!onlyIdentity) results.Add("A_ID", attr_A_ID);
            if (!onlyIdentity) results.Add("NumberOfC", attr_NumberOfC);
            if (!onlyIdentity) results.Add("Kind", attr_Kind);

            return results;
        }

#if false
        List<ChangedState> changedStates = new List<ChangedState>();

        public IList<ChangedState> ChangedStates()
        {
            List<ChangedState> results = new List<ChangedState>();
            results.AddRange(changedStates);
            results.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Update, Target = this, ChangedProperties = ChangedProperties() });
            changedStates.Clear();

            return results;
        }
#endif
    }
}
