// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 1.0.0
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.Utility.Logging;
using Kae.DomainModel.Csharp.Framework;

namespace ActionLogicGenerationTest
{
    public partial class DomainClassCStateMachine : StateMachineBase, ITransition
    {
        public enum Events
        {
            C_1 = 0,     // Create
            C_2 = 1    // Done
        }

        public enum States
        {
            _NoState_ = 0,
            Created = 1,
            Worked = 2
        }

        private interface IEventArgsB_idS_idDef
        {
            public string b_id { get; set; }
            public string s_id { get; set; }
        }
        public class C_1_Create : EventData, IEventArgsB_idS_idDef
        {
            DomainClassC reciever;

            public C_1_Create(DomainClassC reciever) : base("C_1_Create", (int)Events.C_1)
            {
                this.reciever = reciever;
            }

            public override void Send()
            {
                reciever.TakeEvent(this);
            }

            public string b_id { get; set; }
            public string s_id { get; set; }
            public static C_1_Create Create(DomainClassC receiver, string b_id, string s_id, bool isSelfEvent, bool sendNow, InstanceRepository instanceRepository, Logger logger)
            {
                var newEvent = new C_1_Create(receiver) { b_id = b_id, s_id = s_id };
                if (receiver == null && instanceRepository != null)
                {
                    receiver = DomainClassCBase.CreateInstance(instanceRepository, logger);
                }
                if (sendNow)
                {
                    receiver.TakeEvent(newEvent);
                }

                return newEvent;
            }

            public override string GetReceiverIdentities()
            {
                string identiteis = "";
                if (this.reciever != null)
                {
                    identiteis = this.reciever.GetIdForExternalStorage();
                }
                return identiteis;
            }

            public override IDictionary<string, object> GetSupplementalData()
            {
                var supplementalData = new Dictionary<string, object>();

                supplementalData.Add("b_id", b_id);
                supplementalData.Add("s_id", s_id);

                return supplementalData;
            }
        }

        public class C_2_Done : EventData
        {
            DomainClassC reciever;

            public C_2_Done(DomainClassC reciever) : base("C_2_Done", (int)Events.C_2)
            {
                this.reciever = reciever;
            }

            public override void Send()
            {
                reciever.TakeEvent(this);
            }

            public static C_2_Done Create(DomainClassC receiver, bool isSelfEvent, bool sendNow)
            {
                var newEvent = new C_2_Done(receiver);
                if (receiver != null)
                {
                    if (sendNow)
                    {
                        receiver.TakeEvent(newEvent, isSelfEvent);
                    }
                }
                else
                {
                    if (sendNow)
                    {
                        newEvent = null;
                    }
                }

                return newEvent;
            }

            public override string GetReceiverIdentities()
            {
                string identiteis = "";
                if (this.reciever != null)
                {
                    identiteis = this.reciever.GetIdForExternalStorage();
                }
                return identiteis;
            }

            public override IDictionary<string, object> GetSupplementalData()
            {
                var supplementalData = new Dictionary<string, object>();


                return supplementalData;
            }
        }

        protected DomainClassC target;

        protected InstanceRepository instanceRepository;

        protected string DomainName { get { return target.DomainName; } }

        // Constructor
        public DomainClassCStateMachine(DomainClassC target, bool synchronousMode, InstanceRepository instanceRepository, Logger logger) : base(0, synchronousMode, logger)
        {
            this.target = target;
            this.stateTransition = this;
            this.logger = logger;
            this.instanceRepository = instanceRepository;
        }

        protected int[,] stateTransitionTable = new int[2, 2]
            {
                { (int)ITransition.Transition.CantHappen, (int)States.Worked }, 
                { (int)ITransition.Transition.CantHappen, (int)ITransition.Transition.CantHappen }
            };

        public int GetNextState(int currentState, int eventNumber)
        {
            return stateTransitionTable[currentState, eventNumber];
        }

        private List<ChangedState> changedStates;

        protected override void RunEntryAction(int nextState, EventData eventData)
        {
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:C(C_ID={target.Attr_C_ID}):entering[current={CurrentState},event={eventData.EventNumber}");


            changedStates = new List<ChangedState>();

            switch (nextState)
            {
            case (int)States.Created:
                ActionCreated(((IEventArgsB_idS_idDef)eventData).b_id, ((IEventArgsB_idS_idDef)eventData).s_id);
                break;
            case (int)States.Worked:
                ActionWorked();
                break;
            }
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:C(C_ID={target.Attr_C_ID}):entered[current={CurrentState},event={eventData.EventNumber}");


            instanceRepository.SyncChangedStates(changedStates);
        }
    }
}
