// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 1.0.0
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.Utility.Logging;
using Kae.DomainModel.Csharp.Framework;
using Kae.DomainModel.Csharp.Framework.Adaptor.ExternalStorage;

namespace ActionLogicGenerationTest
{
    public partial class DomainClassSBase : DomainClassS
    {
        protected static readonly string className = "S";

        public string DomainName { get { return CIMActionLogicGenerationTestLib.DomainName; }}
        public string ClassName { get { return className; } }

        InstanceRepository instanceRepository;
        protected Logger logger;


        public string GetIdForExternalStorage() {  return $"S_ID={attr_S_ID}"; }

        public static DomainClassSBase CreateInstance(InstanceRepository instanceRepository, Logger logger=null, IList<ChangedState> changedStates=null, bool synchronousMode = false)
        {
            var newInstance = new DomainClassSBase(instanceRepository, logger, synchronousMode);
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:S(S_ID={newInstance.Attr_S_ID}):create");

            instanceRepository.Add(newInstance);

            if (changedStates !=null) changedStates.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Create, Target = newInstance, ChangedProperties = null });

            return newInstance;
        }

        public DomainClassSBase(InstanceRepository instanceRepository, Logger logger, bool synchronousMode)
        {
            this.instanceRepository = instanceRepository;
            this.logger = logger;
            attr_S_ID = Guid.NewGuid().ToString();
            stateof_S_ID = true;
        }
        protected string attr_S_ID;
        protected bool stateof_S_ID = false;

        public string Attr_S_ID { get { return attr_S_ID; } set { attr_S_ID = value; stateof_S_ID = true; } }


        // This method can be used as compare predicattion when calling InstanceRepository's SelectInstances method. 
        public static bool Compare(DomainClassS instance, IDictionary<string, object> conditionPropertyValues)
        {
            bool result = true;
            foreach (var propertyName in conditionPropertyValues.Keys)
            {
                switch (propertyName)
                {
                    case "S_ID":
                        if ((string)conditionPropertyValues[propertyName] != instance.Attr_S_ID)
                        {
                            result = false;
                        }
                        break;
                }
                if (result== false)
                {
                    break;
                }
            }
            return result;
        }

        public IEnumerable<DomainClassR> LinkedR5One()
        {
            var result = new List<DomainClassR>();
            var candidates = instanceRepository.GetDomainInstances("R").Where(inst=>(this.Attr_S_ID==((DomainClassR)inst).Attr_S_ID));
            if (instanceRepository.ExternalStorageAdaptor != null) candidates = instanceRepository.ExternalStorageAdaptor.CheckTraverseStatus(DomainName, this, "R", "R5_", candidates, () => { return DomainClassRBase.CreateInstance(instanceRepository, logger); }, "many").Result;
            foreach (var c in candidates)
            {
                ((DomainClassR)c).LinkedR5Other();
                result.Add((DomainClassR)c);
            }
            return result;
        }


        public SubClassR6 GetSubR6()
        {
            SubClassR6 result = null;
            var subClassKeys = new List<string>() { "CX", "CY" };
            foreach (var key in subClassKeys)
            {
                var candidates = instanceRepository.GetDomainInstances(key).Where(inst=>((this == ((SubClassR6)inst).GetSuperClassR6())));
                if (instanceRepository.ExternalStorageAdaptor != null)  candidates = instanceRepository.ExternalStorageAdaptor.CheckInstanceStatus(DomainName, key, candidates, () => { return "S_ID = '{this.Attr_S_ID}'"; }, () => { return SubClassR6Factory.CreateInstance(key, instanceRepository, logger); }, "any").Result;
                if (candidates.Count() > 0)
                {
                    result = (SubClassR6)candidates.FirstOrDefault();
                    result.GetSuperClassR6();
                    break;
                }
            }
            return result;
        }


        public DomainClassCX LinkedR6CX()
        {
            return (DomainClassCX)GetSubR6();
        }


        public DomainClassCY LinkedR6CY()
        {
            return (DomainClassCY)GetSubR6();
        }



        
        public bool Validate()
        {
            bool isValid = true;
            if (this.GetSubR6() == null)
            {
                isValid = false;
            }
            return isValid;
        }

        public void DeleteInstance(IList<ChangedState> changedStates=null)
        {
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:S(S_ID={this.Attr_S_ID}):delete");

            changedStates.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Delete, Target = this, ChangedProperties = null });

            instanceRepository.Delete(this);
        }

        // methods for storage
        public void Restore(IDictionary<string, object> propertyValues)
        {
            if (propertyValues.ContainsKey("S_ID"))
            {
// should adopt timer setting
                attr_S_ID = (string)propertyValues["S_ID"];
            }
            stateof_S_ID = false;
        }
        
        public IDictionary<string, object> ChangedProperties()
        {
            var results = new Dictionary<string, object>();
            if (stateof_S_ID)
            {
                results.Add("S_ID", attr_S_ID);
                stateof_S_ID = false;
            }

            return results;
        }

        public string GetIdentities()
        {
            string identities = $"S_ID={this.Attr_S_ID}";

            return identities;
        }
        
        public IDictionary<string, object> GetProperties(bool onlyIdentity)
        {
            var results = new Dictionary<string, object>();

            if (!onlyIdentity) results.Add("S_ID", attr_S_ID);

            return results;
        }

#if false
        List<ChangedState> changedStates = new List<ChangedState>();

        public IList<ChangedState> ChangedStates()
        {
            List<ChangedState> results = new List<ChangedState>();
            results.AddRange(changedStates);
            results.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Update, Target = this, ChangedProperties = ChangedProperties() });
            changedStates.Clear();

            return results;
        }
#endif
    }
}
