// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 1.0.0
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.Utility.Logging;
using Kae.DomainModel.Csharp.Framework;
using Kae.DomainModel.Csharp.Framework.Adaptor.ExternalStorage;

namespace ActionLogicGenerationTest
{
    public partial class DomainClassRBase : DomainClassR
    {
        protected static readonly string className = "R";

        public string DomainName { get { return CIMActionLogicGenerationTestLib.DomainName; }}
        public string ClassName { get { return className; } }

        InstanceRepository instanceRepository;
        protected Logger logger;


        public string GetIdForExternalStorage() {  return $"D_ID={attr_D_ID};S_ID={attr_S_ID}"; }

        public static DomainClassRBase CreateInstance(InstanceRepository instanceRepository, Logger logger=null, IList<ChangedState> changedStates=null, bool synchronousMode = false)
        {
            var newInstance = new DomainClassRBase(instanceRepository, logger, synchronousMode);
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:R(D_ID={newInstance.Attr_D_ID},S_ID={newInstance.Attr_S_ID}):create");

            instanceRepository.Add(newInstance);

            if (changedStates !=null) changedStates.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Create, Target = newInstance, ChangedProperties = null });

            return newInstance;
        }

        public DomainClassRBase(InstanceRepository instanceRepository, Logger logger, bool synchronousMode)
        {
            this.instanceRepository = instanceRepository;
            this.logger = logger;
        }
        protected string attr_D_ID;
        protected bool stateof_D_ID = false;

        protected string attr_S_ID;
        protected bool stateof_S_ID = false;

        public string Attr_D_ID { get { return attr_D_ID; } }
        public string Attr_S_ID { get { return attr_S_ID; } }


        // This method can be used as compare predicattion when calling InstanceRepository's SelectInstances method. 
        public static bool Compare(DomainClassR instance, IDictionary<string, object> conditionPropertyValues)
        {
            bool result = true;
            foreach (var propertyName in conditionPropertyValues.Keys)
            {
                switch (propertyName)
                {
                    case "D_ID":
                        if ((string)conditionPropertyValues[propertyName] != instance.Attr_D_ID)
                        {
                            result = false;
                        }
                        break;
                    case "S_ID":
                        if ((string)conditionPropertyValues[propertyName] != instance.Attr_S_ID)
                        {
                            result = false;
                        }
                        break;
                }
                if (result== false)
                {
                    break;
                }
            }
            return result;
        }
        protected LinkedInstance relR5D;
        // private DomainClassD relR5D;
        protected LinkedInstance relR5S;
        // private DomainClassS relR5S;
        public bool LinkR5(DomainClassD oneInstance, DomainClassS otherInstance, IList<ChangedState> changedStates=null)
        {
            bool result = false;
            if (relR5D == null && relR5S == null)
            {
                this.attr_D_ID = oneInstance.Attr_D_ID;
                this.stateof_D_ID = true;
                this.attr_S_ID = otherInstance.Attr_S_ID;
                this.stateof_S_ID = true;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:R(D_ID={this.Attr_D_ID},S_ID={this.Attr_S_ID}):link[One(D(D_ID={oneInstance.Attr_D_ID})),Other(S(S_ID={otherInstance.Attr_S_ID}))]");

                result = (LinkedR5One()!=null) && (LinkedR5Other()!=null);
                if (result)
                {
                    if (changedStates != null)
                    {
                        changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Create, Target = relR5D });
                        changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Create, Target = relR5S });
                    }
                }
            }
            return result;
        }
        
        public bool UnlinkR5(DomainClassD oneInstance, DomainClassS otherInstance, IList<ChangedState> changedStates=null)
        {
            bool result = false;
            if (relR5D != null && relR5S != null)
            {
                if ((this.Attr_D_ID==oneInstance.Attr_D_ID) && (this.Attr_S_ID==otherInstance.Attr_S_ID))
                {
                    if (changedStates != null)
                    {
                        changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Delete, Target = relR5D });
                        changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Delete, Target = relR5S });
                    }
        
                    this.attr_D_ID = null;
                    this.stateof_D_ID = true;
                    this.attr_S_ID = null;
                    this.stateof_S_ID = true;
                    relR5D = null;
                    relR5S = null;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:R(D_ID={this.Attr_D_ID},S_ID={this.Attr_S_ID}):unlink[D(D_ID={oneInstance.Attr_D_ID})]");

                    result = true;
                }
            }
            return result;
        }
        
        public DomainClassD LinkedR5One()
        {
            if (relR5D == null)
            {
                var candidates = instanceRepository.GetDomainInstances("D").Where(inst=>(this.Attr_D_ID==((DomainClassD)inst).Attr_D_ID));
                if (candidates.Count() == 0)
                {
                   if (instanceRepository.ExternalStorageAdaptor != null) candidates = instanceRepository.ExternalStorageAdaptor.CheckTraverseStatus(DomainName, this, "D", "R5_", candidates, () => { return DomainClassDBase.CreateInstance(instanceRepository, logger); }, "any").Result;
                }
                relR5D = new LinkedInstance() { Source = this, Destination = candidates.FirstOrDefault(), RelationshipID = "R5", Phrase = "" };
                // (DomainClassD)candidates.FirstOrDefault();
            }
            return relR5D.GetDestination<DomainClassD>();
        }
        
        public DomainClassS LinkedR5Other()
        {
            if (relR5S == null)
            {
                var candidates = instanceRepository.GetDomainInstances("S").Where(inst=>(this.Attr_S_ID==((DomainClassS)inst).Attr_S_ID));
                if (candidates.Count() == 0)
                {
                   if (instanceRepository.ExternalStorageAdaptor != null) candidates = instanceRepository.ExternalStorageAdaptor.CheckTraverseStatus(DomainName, this, "S", "R5_", candidates, () => { return DomainClassSBase.CreateInstance(instanceRepository, logger); }, "any").Result;
                }
                relR5S = new LinkedInstance() { Source = this, Destination = candidates.FirstOrDefault(), RelationshipID = "R5", Phrase = "" };
                // (DomainClassS)candidates.FirstOrDefault();
            }
            return relR5S.GetDestination<DomainClassS>();
        }



        
        public bool Validate()
        {
            bool isValid = true;
            if (relR5D == null)
            {
                isValid = false;
            }
            if (relR5S == null)
            {
                isValid = false;
            }
            return isValid;
        }

        public void DeleteInstance(IList<ChangedState> changedStates=null)
        {
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:R(D_ID={this.Attr_D_ID},S_ID={this.Attr_S_ID}):delete");

            changedStates.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Delete, Target = this, ChangedProperties = null });

            instanceRepository.Delete(this);
        }

        // methods for storage
        public void Restore(IDictionary<string, object> propertyValues)
        {
            if (propertyValues.ContainsKey("D_ID"))
            {
// should adopt timer setting
                attr_D_ID = (string)propertyValues["D_ID"];
            }
            stateof_D_ID = false;
            if (propertyValues.ContainsKey("S_ID"))
            {
// should adopt timer setting
                attr_S_ID = (string)propertyValues["S_ID"];
            }
            stateof_S_ID = false;
        }
        
        public IDictionary<string, object> ChangedProperties()
        {
            var results = new Dictionary<string, object>();
            if (stateof_D_ID)
            {
                results.Add("D_ID", attr_D_ID);
                stateof_D_ID = false;
            }
            if (stateof_S_ID)
            {
                results.Add("S_ID", attr_S_ID);
                stateof_S_ID = false;
            }

            return results;
        }

        public string GetIdentities()
        {
            string identities = $"D_ID={this.Attr_D_ID},S_ID={this.Attr_S_ID}";

            return identities;
        }
        
        public IDictionary<string, object> GetProperties(bool onlyIdentity)
        {
            var results = new Dictionary<string, object>();

            if (!onlyIdentity) results.Add("D_ID", attr_D_ID);
            if (!onlyIdentity) results.Add("S_ID", attr_S_ID);

            return results;
        }

#if false
        List<ChangedState> changedStates = new List<ChangedState>();

        public IList<ChangedState> ChangedStates()
        {
            List<ChangedState> results = new List<ChangedState>();
            results.AddRange(changedStates);
            results.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Update, Target = this, ChangedProperties = ChangedProperties() });
            changedStates.Clear();

            return results;
        }
#endif
    }
}
