// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 1.0.0
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.Utility.Logging;
using Kae.DomainModel.Csharp.Framework;
using Kae.DomainModel.Csharp.Framework.Adaptor.ExternalStorage;

namespace ActionLogicGenerationTest
{
    public partial class DomainClassCXBase : DomainClassCX
    {
        protected static readonly string className = "CX";

        public string DomainName { get { return CIMActionLogicGenerationTestLib.DomainName; }}
        public string ClassName { get { return className; } }

        InstanceRepository instanceRepository;
        protected Logger logger;


        public string GetIdForExternalStorage() {  return $"S_ID={attr_S_ID}"; }

        public static DomainClassCXBase CreateInstance(InstanceRepository instanceRepository, Logger logger=null, IList<ChangedState> changedStates=null, bool synchronousMode = false)
        {
            var newInstance = new DomainClassCXBase(instanceRepository, logger, synchronousMode);
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:CX(S_ID={newInstance.Attr_S_ID}):create");

            instanceRepository.Add(newInstance);

            if (changedStates !=null) changedStates.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Create, Target = newInstance, ChangedProperties = null });

            return newInstance;
        }

        public DomainClassCXBase(InstanceRepository instanceRepository, Logger logger, bool synchronousMode)
        {
            this.instanceRepository = instanceRepository;
            this.logger = logger;
        }
        protected string attr_S_ID;
        protected bool stateof_S_ID = false;

        protected string attr_C_ID;
        protected bool stateof_C_ID = false;

        public string Attr_S_ID { get { return attr_S_ID; } }
        public string Attr_C_ID { get { return attr_C_ID; } }


        // This method can be used as compare predicattion when calling InstanceRepository's SelectInstances method. 
        public static bool Compare(DomainClassCX instance, IDictionary<string, object> conditionPropertyValues)
        {
            bool result = true;
            foreach (var propertyName in conditionPropertyValues.Keys)
            {
                switch (propertyName)
                {
                    case "S_ID":
                        if ((string)conditionPropertyValues[propertyName] != instance.Attr_S_ID)
                        {
                            result = false;
                        }
                        break;
                    case "C_ID":
                        if ((string)conditionPropertyValues[propertyName] != instance.Attr_C_ID)
                        {
                            result = false;
                        }
                        break;
                }
                if (result== false)
                {
                    break;
                }
            }
            return result;
        }
        protected LinkedInstance relR6S;
        protected LinkedInstance relR7CIsTargetOf;
        public DomainClassS GetSuperClassR6()
        {
            if (relR6S == null)
            {
                var candidates = instanceRepository.GetDomainInstances("S").Where(inst => (this.Attr_S_ID==((DomainClassS)inst).Attr_S_ID));
                if (candidates.Count() == 0)
                {
                   if (instanceRepository.ExternalStorageAdaptor != null) candidates = instanceRepository.ExternalStorageAdaptor.CheckTraverseStatus(DomainName, this, "S", "R6_CX", candidates, () => { return DomainClassSBase.CreateInstance(instanceRepository, logger); }, "any").Result;
                }
                relR6S = new LinkedInstance() { Source = this, Destination = candidates.FirstOrDefault(), RelationshipID = "R6", Phrase = null };
            }
            return relR6S.GetDestination<DomainClassS>();
        }

        public bool LinkR6(DomainClassS instance, IList<ChangedState> changedStates=null)
        {
            bool result = false;
            if (relR6S == null)
            {
                this.attr_S_ID = instance.Attr_S_ID;
                this.stateof_S_ID = true;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:CX(S_ID={this.Attr_S_ID}):link[S(S_ID={instance.Attr_S_ID})]");

                result = (GetSuperClassR6()!=null);
                if (result)
                {
                    if (changedStates != null) changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Create, Target = relR6S });
                }
            }
            return result;
        }
        
        public bool UnlinkR6(DomainClassS instance, IList<ChangedState> changedStates=null)
        {
            bool result = false;
            if (relR6S != null && ( this.Attr_S_ID==instance.Attr_S_ID ))
            {
                if (changedStates != null) changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Delete, Target = relR6S });
        
                this.attr_S_ID = null;
                this.stateof_S_ID = true;
                relR6S = null;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:CX(S_ID={this.Attr_S_ID}):unlink[S(S_ID={instance.Attr_S_ID})]");

                result = true;
            }
            return result;
        }

        public DomainClassC LinkedR7IsTargetOf()
        {
            if (relR7CIsTargetOf == null)
            {
                var candidates = instanceRepository.GetDomainInstances("C").Where(inst=>(this.Attr_C_ID==((DomainClassC)inst).Attr_C_ID));
                if (candidates.Count() == 0)
                {
                   if (instanceRepository.ExternalStorageAdaptor != null) candidates = instanceRepository.ExternalStorageAdaptor.CheckTraverseStatus(DomainName, this, "C", "R7", candidates, () => { return DomainClassCBase.CreateInstance(instanceRepository, logger); }, "any").Result;
                }
                relR7CIsTargetOf = new LinkedInstance() { Source = this, Destination = candidates.FirstOrDefault(), RelationshipID = "R7", Phrase = "IsTargetOf" };

            }
            return relR7CIsTargetOf.GetDestination<DomainClassC>();
        }

        public bool LinkR7IsTargetOf(DomainClassC instance, IList<ChangedState> changedStates=null)
        {
            bool result = false;
            if (relR7CIsTargetOf == null)
            {
                this.attr_C_ID = instance.Attr_C_ID;
                this.stateof_C_ID = true;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:CX(S_ID={this.Attr_S_ID}):link[C(C_ID={instance.Attr_C_ID})]");

                result = (LinkedR7IsTargetOf()!=null);
                if (result)
                {
                    if(changedStates != null) changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Create, Target = relR7CIsTargetOf });
                }
            }
            return result;
        }

        public bool UnlinkR7IsTargetOf(DomainClassC instance, IList<ChangedState> changedStates=null)
        {
            bool result = false;
            if (relR7CIsTargetOf != null && ( this.Attr_C_ID==instance.Attr_C_ID ))
            {
                if (changedStates != null) changedStates.Add(new CLinkChangedState() { OP = ChangedState.Operation.Delete, Target = relR7CIsTargetOf });
        
                this.attr_C_ID = null;
                this.stateof_C_ID = true;
                relR7CIsTargetOf = null;

                if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:CX(S_ID={this.Attr_S_ID}):unlink[C(C_ID={instance.Attr_C_ID})]");


                result = true;
            }
            return result;
        }


        
        public bool Validate()
        {
            bool isValid = true;
            if (relR6S == null)
            {
                isValid = false;
            }
            return isValid;
        }

        public void DeleteInstance(IList<ChangedState> changedStates=null)
        {
            if (logger != null) logger.LogInfo($"@{DateTime.Now.ToString("yyyyMMddHHmmss.fff")}:CX(S_ID={this.Attr_S_ID}):delete");

            changedStates.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Delete, Target = this, ChangedProperties = null });

            instanceRepository.Delete(this);
        }

        // methods for storage
        public void Restore(IDictionary<string, object> propertyValues)
        {
            if (propertyValues.ContainsKey("S_ID"))
            {
// should adopt timer setting
                attr_S_ID = (string)propertyValues["S_ID"];
            }
            stateof_S_ID = false;
            if (propertyValues.ContainsKey("C_ID"))
            {
// should adopt timer setting
                attr_C_ID = (string)propertyValues["C_ID"];
            }
            stateof_C_ID = false;
        }
        
        public IDictionary<string, object> ChangedProperties()
        {
            var results = new Dictionary<string, object>();
            if (stateof_S_ID)
            {
                results.Add("S_ID", attr_S_ID);
                stateof_S_ID = false;
            }
            if (stateof_C_ID)
            {
                results.Add("C_ID", attr_C_ID);
                stateof_C_ID = false;
            }

            return results;
        }

        public string GetIdentities()
        {
            string identities = $"S_ID={this.Attr_S_ID}";

            return identities;
        }
        
        public IDictionary<string, object> GetProperties(bool onlyIdentity)
        {
            var results = new Dictionary<string, object>();

            if (!onlyIdentity) results.Add("S_ID", attr_S_ID);
            if (!onlyIdentity) results.Add("C_ID", attr_C_ID);

            return results;
        }

#if false
        List<ChangedState> changedStates = new List<ChangedState>();

        public IList<ChangedState> ChangedStates()
        {
            List<ChangedState> results = new List<ChangedState>();
            results.AddRange(changedStates);
            results.Add(new CInstanceChagedState() { OP = ChangedState.Operation.Update, Target = this, ChangedProperties = ChangedProperties() });
            changedStates.Clear();

            return results;
        }
#endif
    }
}
