// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 1.0.0
//  
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.DomainModel.Csharp.Framework;
using Kae.DomainModel.Csharp.Framework.Adaptor.ExternalStorage;

namespace ActionLogicGenerationTest
{
    partial class DomainClassBBase
    {
        public void ChangeKind()
        {
            // TODO : Let's write code!
            // Action Description on Model as a reference
            //  1 : IF SELF.Kind == KindOfB::Kind1
            //  2 : 	SELF.Kind = KindOfB::Kind2;
            //  3 : ELIF SELF.Kind == KindOfB::Kind2
            //  4 : 	SELF.Kind = KindOfB::Kind3;
            //  5 : ELIF SELF.Kind == KindOfB::Kind3
            //  6 : 	SELF.Kind = KindOfB::Kind1;
            //  7 : END IF;

            var changedStates = new List<ChangedState>();
            // Generated from action description
                // Line : 1
                if ((this.Attr_Kind == DomainTypeKindOfB.Kind1))
                {
                    // Line : 2
                    this.Attr_Kind = DomainTypeKindOfB.Kind2;
                }
                else if ((this.Attr_Kind == DomainTypeKindOfB.Kind2))
                {
                    // Line : 4
                    this.Attr_Kind = DomainTypeKindOfB.Kind3;
                }
                else if ((this.Attr_Kind == DomainTypeKindOfB.Kind3))
                {
                    // Line : 6
                    this.Attr_Kind = DomainTypeKindOfB.Kind1;
                }


        
            instanceRepository.SyncChangedStates(changedStates);
        }


    }
}
