// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 1.0.0
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Kae.DomainModel.Csharp.Framework;
using Kae.Utility.Logging;

namespace ActionLogicGenerationTest
{
    public interface SubClassR6
    {
        public DomainClassS GetSuperClassR6();
    }

    public static class SubClassR6Factory
    {
        public static DomainClassDef CreateInstance(string classKey, InstanceRepository instanceRepository, Logger logger)
        {
            switch (classKey)
            {
                case "CX":
                    return DomainClassCXBase.CreateInstance(instanceRepository, logger);
                case "CY":
                    return DomainClassCYBase.CreateInstance(instanceRepository, logger);
                default:
                    logger.LogError($"Bad class key letter:'{classKey}' for SubClassR4");
                    break;
            }
            return null;
        }
    }
}
